### ISSUE TITLE
panic during cleanup

### ISSUE THREAD

**Issue by redbaron** [zalando-incubator/postgres-operator#446]
While playing with very unhappy setup (missing permissions ,random restarts during PG cluster init, etc), managed to get into this:

```
time="2019-01-09T23:19:17Z" level=info msg="\"DELETE\" event has been queued" cluster-name=dev/acid-test-cluster pkg=controller worker=0
time="2019-01-09T23:19:17Z" level=info msg="deletion of the cluster started" cluster-name=dev/acid-test-cluster pkg=controller worker=0
time="2019-01-09T23:19:17Z" level=debug msg="deleting statefulset" cluster-name=dev/acid-test-cluster pkg=cluster
time="2019-01-09T23:19:17Z" level=warning msg="could not delete statefulset: there is no statefulset in the cluster" cluster-name=dev/acid-test-cluster pkg=cluster
time="2019-01-09T23:19:17Z" level=debug msg="deleting pod disruption budget" cluster-name=dev/acid-test-cluster pkg=cluster
time="2019-01-09T23:19:17Z" level=warning msg="could not delete pod disruption budget: there is no pod disruption budget in the cluster" cluster-name=dev/acid-test-cluster pkg=cluster
time="2019-01-09T23:19:17Z" level=debug msg="deleting endpoint" cluster-name=dev/acid-test-cluster pkg=cluster
time="2019-01-09T23:19:17Z" level=info msg="endpoint \"dev/acid-test-cluster\" has been deleted" cluster-name=dev/acid-test-cluster pkg=cluster
time="2019-01-09T23:19:17Z" level=debug msg="deleting service master" cluster-name=dev/acid-test-cluster pkg=cluster
time="2019-01-09T23:19:17Z" level=info msg="master service \"dev/acid-test-cluster\" has been deleted" cluster-name=dev/acid-test-cluster pkg=cluster
time="2019-01-09T23:19:17Z" level=debug msg="deleting endpoint" cluster-name=dev/acid-test-cluster pkg=cluster
time="2019-01-09T23:19:17Z" level=info msg="endpoint \"dev/acid-test-cluster-repl\" has been deleted" cluster-name=dev/acid-test-cluster pkg=cluster
time="2019-01-09T23:19:17Z" level=debug msg="deleting service replica" cluster-name=dev/acid-test-cluster pkg=cluster
time="2019-01-09T23:19:17Z" level=info msg="replica service \"dev/acid-test-cluster-repl\" has been deleted" cluster-name=dev/acid-test-cluster pkg=cluster
time="2019-01-09T23:19:17Z" level=debug msg="removing leftover Patroni objects (endpoints or configmaps)" cluster-name=dev/acid-test-cluster pkg=cluster
time="2019-01-09T23:19:17Z" level=debug msg="deleting Patroni cluster object \"endpoint\" with name \"dev/acid-test-cluster-config\"" cluster-name=dev/acid-test-cluster pkg=cluster
time="2019-01-09T23:19:17Z" level=info msg="cluster has been deleted" cluster-name=dev/acid-test-cluster pkg=controller worker=0
time="2019-01-09T23:20:26Z" level=info msg="\"ADD\" event has been queued" cluster-name=dev/acid-test-cluster pkg=controller worker=0
time="2019-01-09T23:20:26Z" level=warning msg="Parameter \"maintenanceWindows\" takes no effect. Not implemented." pkg=controller
time="2019-01-09T23:20:26Z" level=info msg="creation of the cluster started" cluster-name=dev/acid-test-cluster pkg=controller worker=0
time="2019-01-09T23:20:26Z" level=error msg="could not create cluster: could not create master endpoint: could not create master endpoint: endpoints \"acid-test-cluster\" already exists" cluster-name=dev/acid-test-cluster pkg=controller worker=0
time="2019-01-09T23:21:29Z" level=info msg="\"DELETE\" event has been queued" cluster-name=dev/acid-test-cluster pkg=controller worker=0
time="2019-01-09T23:21:29Z" level=info msg="deletion of the cluster started" cluster-name=dev/acid-test-cluster pkg=controller worker=0
time="2019-01-09T23:21:29Z" level=debug msg="deleting statefulset" cluster-name=dev/acid-test-cluster pkg=cluster worker=0
time="2019-01-09T23:21:29Z" level=warning msg="could not delete statefulset: there is no statefulset in the cluster" cluster-name=dev/acid-test-cluster pkg=cluster worker=0
time="2019-01-09T23:21:29Z" level=debug msg="deleting pod disruption budget" cluster-name=dev/acid-test-cluster pkg=cluster worker=0
time="2019-01-09T23:21:29Z" level=warning msg="could not delete pod disruption budget: there is no pod disruption budget in the cluster" cluster-name=dev/acid-test-cluster pkg=cluster worker=0
time="2019-01-09T23:21:29Z" level=debug msg="deleting endpoint" cluster-name=dev/acid-test-cluster pkg=cluster worker=0
time="2019-01-09T23:21:29Z" level=warning msg="could not delete master endpoint: there is no master endpoint in the cluster" cluster-name=dev/acid-test-cluster pkg=cluster worker=0
time="2019-01-09T23:21:29Z" level=debug msg="deleting service master" cluster-name=dev/acid-test-cluster pkg=cluster worker=0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1232c3c]

goroutine 30 [running]:
github.com/zalando-incubator/postgres-operator/pkg/cluster.(*Cluster).deleteService(0xc000193200, 0x15dcdd4, 0x6, 0xc000a47910, 0x2)
	/go/src/github.com/zalando-incubator/postgres-operator/pkg/cluster/resources.go:442 +0x12c
github.com/zalando-incubator/postgres-operator/pkg/cluster.(*Cluster).Delete(0xc000193200)
	/go/src/github.com/zalando-incubator/postgres-operator/pkg/cluster/cluster.go:623 +0x667
github.com/zalando-incubator/postgres-operator/pkg/controller.(*Controller).processEvent(0xc0000d6000, 0xbf05be5e5f1f35c6, 0x34bfacf622, 0x256a200, 0xc000522f30, 0x24, 0x15dc342, 0x6, 0xc0003dcc00, 0x0, ...)
	/go/src/github.com/zalando-incubator/postgres-operator/pkg/controller/postgresql.go:264 +0xbd5
github.com/zalando-incubator/postgres-operator/pkg/controller.(*Controller).processClusterEventsQueue(0xc0000d6000, 0x0, 0xc000488660, 0xc000090000)
	/go/src/github.com/zalando-incubator/postgres-operator/pkg/controller/postgresql.go:326 +0x286
created by github.com/zalando-incubator/postgres-operator/pkg/controller.(*Controller).Run
	/go/src/github.com/zalando-incubator/postgres-operator/pkg/controller/controller.go:355 +0x8a
```

**Comment by erthalion** [comment]
Yes, we're aware about this issue and working on that.
